Repository Chartes-TNAH/patrologia_latina-dev, pull requests merged in 2019-04, with the labels that each got.

#76 #25 _ Structuration du fichier selon les recommandations de CapiTains
  data/stoa0040/stoa015/stoa0040.stoa015.opp-lat1.xml
Labels: Clone4Capitainize, enhancement

#95 (stoa0040.stoa009) Résolution des issues #61 et #90
  data/stoa0040/stoa009/stoa0040.stoa009.opp-lat1.xml
Labels: Clone4Capitainize

#153 Capitanisation stoa0040.stoa028
  data/stoa0040/stoa028/stoa0040.stoa028.opp-lat1.xml
Labels: Clone4Capitainize

#49 Branch dev1
  data/stoa0040/stoa007/stoa0040.stoa007.opp-lat1.xml
Labels: OnHold

#68 (sta0040.stoa014b) Résolution des issues #67 #70 et #86
  data/stoa0040/stoa014b/stoa0040.stoa014b.opp-lat1.xml
Labels: OnHold

#159 (stoa0040.stoa034a) Résolution des issues #156, #158 et #160
  data/stoa0040/stoa034a/stoa0040.stoa034a.opp-lat1.xml
Labels: enhancement

#59 stoa0032 enrichit des chapitres manquants
  data/stoa0040/stoa032/__cts__.xml
  data/stoa0040/stoa032/stoa0040.stoa032.opp-lat2.xml
Labels: enhancement
